### ISSUE TITLE
dimension error in  _collect_x_y_matrices function from rs.band_classification function

### ISSUE THREAD

**Issue by MarceloBarrosVanegas** [semiautomaticgit/remotior_sensus#1]
Hi Luca, this is a great effort from your part. I am trying to use the rs.band_classification function, I have this workflow so far.
```

if __name__ == '__main__':
    import remotior_sensus
    
    rs = remotior_sensus.Session(n_processes=16, available_ram=256* 16)
    cfg = rs.configurations
    
    # create BandSet
    catalog = rs.bandset_catalog()
    file_list = ['T17MQS_20230824T153621_B02.tif', 'T17MQS_20230824T153621_B03.tif', 'T17MQS_20230824T153621_B04.tif', 'T17MQS_20230824T153621_B05.tif', 'T17MQS_20230824T153621_B06.tif', 'T17MQS_20230824T153621_B08.tif', 'T17MQS_20230824T153621_B11.tif', 'T17MQS_20230824T153621_B12.tif', 'T17MQS_20230824T153621_B8A.tif']
    
    root_directory = 'data/'
    
    catalog.create_bandset(file_list, wavelengths=['Sentinel-2'], root_directory=root_directory)
    # set BandSet in SpectralCatalog
    signature_catalog_2 = rs.spectral_signatures_catalog(bandset=catalog.get(1))
    # import vector
    signature_catalog_2.import_vector(
        file_path=r'C:\Users\chelo\OneDrive\00_RACAR_FABIAN\land_use.gpkg',
        macroclass_field='macroclass', class_field='LandUseType',
        macroclass_name_field='macroclass', class_name_field='LandUseType',
        calculate_signature=True
    )
    temp = cfg.temp.temporary_file_path(
        name='class', name_suffix=cfg.tif_suffix
    )
    rs.band_classification(
        input_bands=catalog.get(1), output_path=temp,
        spectral_signatures=signature_catalog_2,
        signature_raster=False
    )
```

First I had a error, due to the fact that  in the  ogr could not read a band.tif file, this is the only situation that this does not work, because gdal and rasterio have no problem whit it.  So I modify the function as follows, it worked after that.

```
# get CRS of a raster or vector
def get_crs(path):
    # try vector
    try:
        l_p = ogr.Open(path)
    except:
        l_p =  None
    # if raster
    if l_p is None:
        l_p = gdal.Open(path, gdal.GA_ReadOnly)
        if l_p is None:
            crs = None
        else:
            try:
                # check projections
                crs = l_p.GetProjection()
                crs = crs.replace(' ', '')
                if len(crs) == 0:
                    crs = None
            except Exception as err:
                crs = None
                cfg.logger.log.error(str(err))
    # if vector
    else:
        layer = l_p.GetLayer()
        # get projection
        crs = get_layer_crs(layer)
    cfg.logger.log.debug('path: %s; crs: %s' % (path, crs))
    return crs
```

After this part I have this error, in this function 'Gets x y arrays from rois' wich give me this error.

  File "C:\Users\chelo\OneDrive\ALCANTARILLADO_PyQt5\00_MODULOS\pypiper\borrar.py", line 2873, in <module>
    rs.band_classification(
  File "C:\Users\chelo\miniconda3\Lib\site-packages\remotior_sensus\tools\band_classification.py", line 1280, in band_classification
    x_y_matrices = _collect_x_y_matrices(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chelo\miniconda3\Lib\site-packages\remotior_sensus\tools\band_classification.py", line 1522, in _collect_x_y_matrices
    x_y_arrays = _get_x_y_arrays_from_rois(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chelo\miniconda3\Lib\site-packages\remotior_sensus\tools\band_classification.py", line 1439, in _get_x_y_arrays_from_rois
    matrix = np.stack(array_dictionary[s])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in stack
  File "C:\Users\chelo\miniconda3\Lib\site-packages\numpy\core\shape_base.py", line 464, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source             
libifcoremd.dll    00007FFA8673DF54  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFB048829E3  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFB05707344  Unknown               Unknown  Unknown
ntdll.dll          00007FFB071026B1  Unknown               Unknown  Unknown

Process finished with exit code 0

I have several warnings  as this, but I think that is because of my type of features in the gpkg gile.

` band classification [  1%] [elapsed 1min23sec]:starting the classifier ⚙Warning 1: A geometry of type POLYGON is inserted into layer t20231010_201907039038_8290 of geometry type MULTIPOLYGON, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.`

Glad to see this out, I used the plugin before so this is very useful for me as it let me do whole pipelines adding land use classification

Greetings, 
Marcelo.

**Comment by semiautomaticgit** [comment]
Hi @MarceloBarrosVanegas , I'm glad you are using Remotior Sensus.

> def get_crs(path):
>     # try vector
>     try:
>         l_p = ogr.Open(path)
>     except:
>         l_p =  None
>     # if raster
>     if l_p is None:
>         l_p = gdal.Open(path, gdal.GA_ReadOnly)
>         if l_p is None:
>             crs = None
>         else:
>             try:
>                 # check projections
>                 crs = l_p.GetProjection()
>                 crs = crs.replace(' ', '')
>                 if len(crs) == 0:
>                     crs = None
>             except Exception as err:
>                 crs = None
>                 cfg.logger.log.error(str(err))
>     # if vector
>     else:
>         layer = l_p.GetLayer()
>         # get projection
>         crs = get_layer_crs(layer)
>     cfg.logger.log.debug('path: %s; crs: %s' % (path, crs))
>     return crs

Thank you for posting this, I can fix it in the code.


> File "C:\Users\chelo\OneDrive\ALCANTARILLADO_PyQt5\00_MODULOS\pypiper\borrar.py", line 2873, in rs.band_classification( File "C:\Users\chelo\miniconda3\Lib\site-packages\remotior_sensus\tools\band_classification.py", line 1280, in band_classification x_y_matrices = _collect_x_y_matrices( ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\chelo\miniconda3\Lib\site-packages\remotior_sensus\tools\band_classification.py", line 1522, in _collect_x_y_matrices x_y_arrays = _get_x_y_arrays_from_rois( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\chelo\miniconda3\Lib\site-packages\remotior_sensus\tools\band_classification.py", line 1439, in _get_x_y_arrays_from_rois matrix = np.stack(array_dictionary[s]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<**array_function** internals>", line 200, in stack File "C:\Users\chelo\miniconda3\Lib\site-packages\numpy\core\shape_base.py", line 464, in stack raise ValueError('all input arrays must have the same shape') ValueError: all input arrays must have the same shape forrtl: error (200): program aborting due to control-C event Image PC Routine Line Source libifcoremd.dll 00007FFA8673DF54 Unknown Unknown Unknown KERNELBASE.dll 00007FFB048829E3 Unknown Unknown Unknown KERNEL32.DLL 00007FFB05707344 Unknown Unknown Unknown ntdll.dll 00007FFB071026B1 Unknown Unknown Unknown

Could you check if the ROIs cover the same pixels in all the bands? 
The fact that input arrays don't have the same shape could indicate that some ROIs have different dimensions (not the same number of pixels in all the bands).

> ` band classification [ 1%] [elapsed 1min23sec]:starting the classifier ⚙Warning 1: A geometry of type POLYGON is inserted into layer t20231010_201907039038_8290 of geometry type MULTIPOLYGON, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.`

This is just a warning, should work anyway.

**Comment by MarceloBarrosVanegas** [comment]
I will search for this,

```
Could you check if the ROIs cover the same pixels in all the bands?
The fact that input arrays don't have the same shape could indicate that some ROIs have different dimensions (not the same number of pixels in all the bands).
```

 I don't know the code enough to tell you this right away,  but I will look for it.

Thank you for your time.

**Comment by semiautomaticgit** [comment]
> I will search for this,
> 
> ```
> Could you check if the ROIs cover the same pixels in all the bands?
> The fact that input arrays don't have the same shape could indicate that some ROIs have different dimensions (not the same number of pixels in all the bands).
> ```
> 
> I don't know the code enough to tell you this right away, but I will look for it.
> 
> Thank you for your time.

You are welcome.
I mean that you could load the layers in a GIS environment and check if there are border pixels that are not covered by all the bands.

**Comment by semiautomaticgit** [comment]
Please update Remotior Sensus to version 1.0.04, it should be solved

**Comment by MarceloBarrosVanegas** [comment]
Hi, Luca thanks, I will do this and try it, and let you know. Thanks for responding so quickly.

**Comment by semiautomaticgit** [comment]
I'm closing this, but please reopen if it is still relevant.
