### ISSUE TITLE
When i select the MTL file for Landsat data in image conversion, SCP 8.1.3 shows error message

### ISSUE THREAD

**Issue by claudioasn** [semiautomaticgit/remotior_sensus#2]
When i select the MTL file for Landsat data in image conversion, SCP 8.1.3 shows error message: "Warning: no band found. Check metadata inside the directory". If i process without the metadata, k1 and k2 constants, for example, are not loaded.

**Comment by semiautomaticgit** [comment]
It should be fixed in version 0.1.16. Please reopen if still relevant.
