### ISSUE TITLE
remotior_sensus latest version on OSGEO4W

### ISSUE THREAD

**Issue by claudioasn** [semiautomaticgit/remotior_sensus#5]
Hello! Would it be possible to provide remotior_sensus newest version on OSGeo4W? The latest version available on it is the 0.2.1-1. I use it to manage the QGIS installations in my lab. It would be nice to update it directly from OSGeo4W.

**Comment by semiautomaticgit** [comment]
Hello @claudioasn , thank you for your interest in Remotior Sensus. 
Unfortunately I don't manage the OSGeo4W repository.
